all:
  vars:
    ansible_user: centos
    #user name
    ansible_ssh_private_key_file: ./../../id_rsa
    #chemin vers la clé privée
  children:
    prod:
      hosts: clotilde.long.takima.cloud
      #nom de domaine sur serveur
