- hosts: all
  gather_facts: false
  become: yes

# Install Docker
  tasks:
  - name: Clean packages
    command:
      cmd: dnf clean -y packages
      #desinstalle les anciennes versions

  - name: Install device-mapper-persistent-data
    dnf:
      name: device-mapper-persistent-data
      state: latest

  - name: Install lvm2
    dnf:
      name: lvm2
      state: latest

  - name: add repo docker
    command:
      cmd: sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      #configure le depot

  - name: Install Docker
    dnf:
      name: docker-ce
      state: present
      #installe docker

  #- name: install python3
  #  dnf:
  #    name: python3

  - name: Pip install
    pip:
      name: docker

  - name: Make sure Docker is running
    service: name=docker state=started
    tags: docker
    #verifie que Docker est bien installé

  roles:
    - docker
    #- network
    #- database
    #- app
    #- proxy